[package]
name = "sql-repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chumsky = { version = "=1.0.0-alpha.6" }
clap = { version = "4.4.10", features = ["derive"] }
fancy-regex = "0.12.0"
polars = { version = "0.35.4", features = ["lazy", "strings", "lazy_regex"] }
rustyline = { version = "12.0.0", features = ["derive"] }
