[package]
name = "dfsql"
version = "0.4.0"
edition = "2021"
description = "SQL REPL for Data Frames"
license = "MIT"
repository = "https://github.com/Banyc/dfsql"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chumsky = { version = "=1.0.0-alpha.6" }
clap = { version = "4", features = ["derive"] }
fancy-regex = "0.13"
polars = { version = "0.36", features = [
    "abs",
    "json",
    "lazy",
    "lazy_regex",
    "log",
    "strings",
] }
rustyline = { version = "13", features = ["derive"] }
thiserror = "1"
