[package]
name = "dfsql"
version = "0.16.0"
edition = "2024"
description = "SQL REPL for Data Frames"
license = "MIT"
repository = "https://github.com/Banyc/dfsql"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1", optional = true }
hdv = { version = "0.7", default-features = false, optional = true }
winnow = "1"
clap = { version = "4", features = ["derive"], optional = true }
fancy-regex = { version = "0.18", optional = true }
polars = { version = "0.47", features = [
    "abs",
    "lazy",
    "regex",
    "log",
    "strings",
    "dtype-categorical",
    # https://github.com/pola-rs/polars/issues/22733
    "dtype-i128",
], optional = true }
regex = "1"
rustyline = { version = "18", features = ["derive"], optional = true }
thiserror = "2"

[features]
default = []
polars-backend = ["dep:polars"]
file-ops = ["anyhow", "dep:hdv", "polars/json", "polars-backend"]
cli = ["clap", "fancy-regex", "file-ops", "rustyline"]

[[bin]]
name = "dfsql"
path = "src/main.rs"
required-features = ["cli"]
