[package]
name = "dfsql"
version = "0.3.0"
edition = "2021"
description = "SQL REPL for Data Frames"
license = "MIT"
repository = "https://github.com/Banyc/dfsql"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chumsky = { version = "=1.0.0-alpha.6" }
clap = { version = "4.4.10", features = ["derive"] }
fancy-regex = "0.12.0"
polars = { version = "0.35.4", features = [
    "abs",
    "describe",
    "json",
    "lazy",
    "lazy_regex",
    "strings",
] }
rustyline = { version = "13.0.0", features = ["derive"] }
thiserror = "1.0.50"
